---

- name: Setup NonSeed node(s)
  template:
    src: cockroachdb.secondary.unit.j2
    dest: /etc/systemd/system/cockroachdb.service
    owner: root
    group: root
    mode: 0644
  tags: ['cockroachdb-secondary']
  when: ansible_distribution == 'Ubuntu'


- name: setup cockroachdb systemd
  systemd: 
    daemon_reload: yes
    name: cockroachdb
    state: restarted
    enabled: yes
  tags: ['cockroachdb-secondary']
  when: ansible_distribution == 'Ubuntu'
