---
  

- name: Get CockroachDB
  get_url:
    url: https://binaries.cockroachdb.com/cockroach-v{{ cockroachdb_version }}.linux-amd64.tgz
    dest: /tmp/cockroach-v{{ cockroachdb_version }}.linux-amd64.tgz
  tags: ['cockroachdb']
  when: ansible_distribution == 'Ubuntu'

- name: Unpack CockroachDB
  unarchive:
    src: /tmp/cockroach-v{{ cockroachdb_version }}.linux-amd64.tgz
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: "--strip-components=1" # removes folder name from extracted tgz file
  tags: ['cockroachdb']
  when: ansible_distribution == 'Ubuntu'
